from typing import Final

INVALID_FIELD_STATUS_CODE: Final[int] = 403

NOT_FOUND_STATUS_CODE: Final[int] = 404

DEPENDENCY_PROBLEM_STATUS_CODE: Final[int] = 422

CONFLICT_STATUS_CODE: Final[int] = 409

NOT_ACCEPTABLE_STATUS_CODE: Final[int] = 406
