version: '3'

services:
  mongo:
    container_name: mongo
    image: bitnami/mongodb:5.0.6
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=3GdazDdyDisUBpjY3VGA7zf1BJkZ2A8hazOhOCt4f5U=
      - MONGODB_REPLICA_SET_KEY=3GdazDdyDisUBpjY3VGA7zf1BJkZ2A8hazOhOCt4f5U=
    ports: 
      - "27017:27017"
