version: '3'

services:
  words-api:
    build: ./
    environment:
      MONGO_URI: "mongo:27017"
      MONGO_USER: root
      MONGO_PASS: 3GdazDdyDisUBpjY3VGA7zf1BJkZ2A8hazOhOCt4f5U=
      WORDS_DB: WORDS
      WORDS_COLLECTION: Words
    ports: 
      - "8080:8080"
    depends_on:
      - mongo
  
  mongo:
    container_name: mongo
    image: bitnami/mongodb:5.0.6
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=3GdazDdyDisUBpjY3VGA7zf1BJkZ2A8hazOhOCt4f5U=
      - MONGODB_REPLICA_SET_KEY=3GdazDdyDisUBpjY3VGA7zf1BJkZ2A8hazOhOCt4f5U=
